/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_akuntansi.view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import sistem_akuntansi.Factory;
import sistem_akuntansi.entity.Barang;
import sistem_akuntansi.entity.Jenis;
import sistem_akuntansi.model.BarangModel;
import static sistem_akuntansi.view.JenisData.main;
import static sistem_akuntansi.view.JenisForm.main;

public class BarangForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form BarangForm
     */
    private Barang barang;
    private BarangData barangData;
    private JenisData jenisData;
    private BarangModel barangModel;
    private Connection connection;
    
    public BarangForm(MainMenu main) {
        initComponents();
        connection = Factory.getConnection();
        defaultComponent();
        barang = new Barang();  
         barangData = new BarangData(main, true);
        barangData.setLocationRelativeTo(this);
        jenisData = new JenisData(main, true);
        jenisData.setLocationRelativeTo(this);
        barangModel = new BarangModel(connection);
    }

    private void defaultComponent(){
        textKodeObat.setText(null);
        textNamaObat.setText(null);
        textKodeJenis.setText(null);
        //kurang method date 
       textTanggalKadaluwarsa.setValue(new Date());
     
        textFieldJumlah.setValue(0);
        textFieldHargaBeli.setValue(0);
        textFieldHargaJual.setValue(0);
        textKodeObat.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textKodeObat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textTanggalKadaluwarsa = new javax.swing.JSpinner();
        textNamaObat = new javax.swing.JTextField();
        textFieldJumlah = new javax.swing.JFormattedTextField();
        textFieldHargaBeli = new javax.swing.JFormattedTextField();
        textFieldHargaJual = new javax.swing.JFormattedTextField();
        textKodeJenis = new javax.swing.JTextField();
        buttonJenisFind = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBaru = new javax.swing.JButton();
        buttonObat = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FORM OBAT");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Kode Obat");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nama Obat");

        textKodeObat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Jenis Obat");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal Kadaluwarsa");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Jumlah");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Harga Beli");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Harga Jual");

        textTanggalKadaluwarsa.setModel(new javax.swing.SpinnerDateModel());
        textTanggalKadaluwarsa.setEditor(new javax.swing.JSpinner.DateEditor(textTanggalKadaluwarsa, "dd/MM/yyyy"));

        textFieldJumlah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textFieldJumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldJumlah.setValue(0);

        textFieldHargaBeli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textFieldHargaBeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldHargaBeli.setValue(0);

        textFieldHargaJual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textFieldHargaJual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldHargaJual.setValue(0);

        textKodeJenis.setEnabled(false);

        buttonJenisFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonJenisFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJenisFindActionPerformed(evt);
            }
        });

        buttonTambah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonUbah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonUbah.setText("UBAH");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonBaru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonBaru.setText("BARU");
        buttonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaruActionPerformed(evt);
            }
        });

        buttonObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonObatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTanggalKadaluwarsa)
                            .addComponent(textFieldJumlah)
                            .addComponent(textFieldHargaJual)
                            .addComponent(textFieldHargaBeli)
                            .addComponent(textNamaObat)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonTambah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonUbah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonHapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBaru))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonObat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonJenisFind, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonObat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonJenisFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textTanggalKadaluwarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambah)
                    .addComponent(buttonUbah)
                    .addComponent(buttonHapus)
                    .addComponent(buttonBaru))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        barang.setKode_obat(textKodeObat.getText());
        barang.setNama_obat(textNamaObat.getText());
        barang.setKode_jenis(textKodeJenis.getText());
        //method tanggal kurang
        barang.setTanggal_kadaluwarsa((Date)textTanggalKadaluwarsa.getValue());
        
        barang.setJumlah(Integer.parseInt(textFieldJumlah.getValue().toString()));
        barang.setHarga_beli(Integer.parseInt(textFieldHargaBeli.getValue().toString()));
        barang.setHarga_jual(Integer.parseInt(textFieldHargaJual.getValue().toString()));
        
        try {
            connection.setAutoCommit(false);
            barangModel.insert(barang);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data gagal ditambah", "KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        barang.setKode_obat(textKodeObat.getText());
        barang.setNama_obat(textNamaObat.getText());
        barang.setKode_jenis(textKodeJenis.getText());
        //method tanggal
         barang.setTanggal_kadaluwarsa((Date)textTanggalKadaluwarsa.getValue());
        
        barang.setJumlah(Integer.parseInt(textFieldJumlah.getValue().toString()));
        barang.setHarga_beli(Integer.parseInt(textFieldHargaBeli.getValue().toString()));
        barang.setHarga_jual(Integer.parseInt(textFieldHargaJual.getValue().toString()));
        
        try {
            connection.setAutoCommit(false);
            barangModel.update(barang);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data gagal diubah", "KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        barang.setKode_obat(textKodeObat.getText());
        barang.setNama_obat(textNamaObat.getText());
        barang.setKode_jenis(textKodeJenis.getText());
        //method tanggal kuramg
         barang.setTanggal_kadaluwarsa((Date)textTanggalKadaluwarsa.getValue());
        
        barang.setJumlah(Integer.parseInt(textFieldJumlah.getValue().toString()));
        barang.setHarga_beli(Integer.parseInt(textFieldHargaBeli.getValue().toString()));
        barang.setHarga_jual(Integer.parseInt(textFieldHargaJual.getValue().toString()));
        
        try {  
            connection.setAutoCommit(false);
            barangModel.delete(barang);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus", "KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaruActionPerformed
        // TODO add your handling code here:
          defaultComponent();
    }//GEN-LAST:event_buttonBaruActionPerformed

    private void buttonJenisFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJenisFindActionPerformed
        // TODO add your handling code here:
        jenisData.show();
        Jenis jenis =  jenisData.getDataSelection();
        if (jenis == null) jenis = new Jenis();
        textKodeJenis.setText(jenis.getKode_jenis());
    }//GEN-LAST:event_buttonJenisFindActionPerformed

    private void buttonObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonObatActionPerformed
        // TODO add your handling code here:
        barangData.show();
        Barang barang = barangData.getDataSelection();
        if (barang == null) {
            barang = new Barang();
        }
        textKodeObat.setText(barang.getKode_obat());
        textNamaObat.setText(barang.getNama_obat());
        textKodeJenis.setText(barang.getKode_jenis());
        textTanggalKadaluwarsa.setValue(barang.getTanggal_kadaluwarsa());
        textFieldHargaBeli.setValue(barang.getHarga_beli());
        textFieldHargaJual.setValue(barang.getHarga_jual());
        textFieldJumlah.setValue(barang.getJumlah());
    }//GEN-LAST:event_buttonObatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainMenu frame = new MainMenu();
        BarangForm form = new BarangForm(frame);
        frame.setVisible(true);
        frame.desktopPane.add(form);
        form.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBaru;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonJenisFind;
    private javax.swing.JButton buttonObat;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField textFieldHargaBeli;
    private javax.swing.JFormattedTextField textFieldHargaJual;
    private javax.swing.JFormattedTextField textFieldJumlah;
    private javax.swing.JTextField textKodeJenis;
    private javax.swing.JTextField textKodeObat;
    private javax.swing.JTextField textNamaObat;
    private javax.swing.JSpinner textTanggalKadaluwarsa;
    // End of variables declaration//GEN-END:variables
}
