/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_akuntansi.view;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import sistem_akuntansi.Factory;
import sistem_akuntansi.entity.JurnalTransaksi;
import sistem_akuntansi.entity.KasKeluar;
import sistem_akuntansi.entity.KasKeluarDetail;
import sistem_akuntansi.entity.Perkiraan;
import sistem_akuntansi.model.JurnalTransaksiModel;
import sistem_akuntansi.model.KasKeluarDetailModel;
import sistem_akuntansi.model.KasKeluarDetailTableModel;
import sistem_akuntansi.model.KasKeluarModel;

/**
 *
 * @author arochman.aryanta
 */
public class KasKeluarForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form KasKeluarForm
     */
    
    private Connection connection;
    private PerkiraanData perkiraanData;
    private KasKeluarDetailTableModel kasKeluarDetailTableModel;
    
    private final KasKeluarModel kasKeluarModel;    
    private final KasKeluarDetailModel kasKeluarDetailModel;    
    private final JurnalTransaksiModel jurnalTransaksiModel;
    
    public KasKeluarForm(MainMenu main) {  
        initComponents();
        connection = Factory.getConnection();
        
        perkiraanData = new PerkiraanData(main, true);
        perkiraanData.setLocationRelativeTo(this);
        
        kasKeluarDetailTableModel = new KasKeluarDetailTableModel(new Vector<KasKeluarDetail>());
        tabelPengeluaran.setModel(kasKeluarDetailTableModel);
        
        kasKeluarModel = new KasKeluarModel(connection);
        kasKeluarDetailModel = new KasKeluarDetailModel(connection);
        jurnalTransaksiModel = new JurnalTransaksiModel(connection);
        restructurTable();
        buttonBaruActionPerformed(null);
    }
    
    private void restructurTable(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        
        //pengaturan kolom
        tabelPengeluaran.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        tabelPengeluaran.getColumnModel().getColumn(0).setPreferredWidth(40);
        tabelPengeluaran.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelPengeluaran.getColumnModel().getColumn(2).setPreferredWidth(60);       
    }
    
    public Integer getTotal(){
        Integer total= 0;
        for (KasKeluarDetail jurnalDetail : kasKeluarDetailTableModel.getData()) {
            total = total + jurnalDetail.getJumlah();                    
        }
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textKodePenerimaan = new javax.swing.JTextField();
        textNamaPenerimaan = new javax.swing.JTextField();
        buttonPerkiraanFind2 = new javax.swing.JButton();
        buttonSisipkan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buttonHapus = new javax.swing.JButton();
        textJumlah = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textKodeKas = new javax.swing.JTextField();
        buttonPerkiraanFind1 = new javax.swing.JButton();
        textTanggal = new javax.swing.JSpinner();
        textKeterangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNamaKas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNomor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPengeluaran = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        textTotal = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        buttonBaru = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("KAS KELUAR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Rekening pengeluaran");

        textKodePenerimaan.setEditable(false);

        textNamaPenerimaan.setEditable(false);

        buttonPerkiraanFind2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonPerkiraanFind2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerkiraanFind2ActionPerformed(evt);
            }
        });

        buttonSisipkan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSisipkan.setText("SISIPKAN");
        buttonSisipkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSisipkanActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah");

        buttonHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        textJumlah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textJumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textJumlah.setValue(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textKodePenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNamaPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPerkiraanFind2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSisipkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKodePenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNamaPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPerkiraanFind2)
                    .addComponent(buttonSisipkan)
                    .addComponent(buttonHapus)
                    .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Rekening kas");

        textKodeKas.setEditable(false);
        textKodeKas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKodeKasActionPerformed(evt);
            }
        });

        buttonPerkiraanFind1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonPerkiraanFind1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerkiraanFind1ActionPerformed(evt);
            }
        });

        textTanggal.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        textTanggal.setEditor(new javax.swing.JSpinner.DateEditor(textTanggal, "dd/MM/yyyy"));

        jLabel3.setText("Keterangan");

        textNamaKas.setEditable(false);

        jLabel2.setText("Tanggal");

        jLabel7.setText("Nomor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textKodeKas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNamaKas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPerkiraanFind1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textKodeKas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNamaKas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPerkiraanFind1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabelPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengeluaranMouseClicked(evt);
            }
        });
        tabelPengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelPengeluaranKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPengeluaran);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        textTotal.setEditable(false);
        textTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalActionPerformed(evt);
            }
        });
        textTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTotalKeyTyped(evt);
            }
        });

        jLabel6.setText("TOTAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonBaru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonBaru.setText("BARU");
        buttonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaruActionPerformed(evt);
            }
        });

        buttonSimpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonCetak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCetak.setText("CETAK");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSimpan)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBaru)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonCetak))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPerkiraanFind1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerkiraanFind1ActionPerformed
        // TODO add your handling code here:
        perkiraanData.show();
        Perkiraan perkiraan = perkiraanData.getDataSelection();
        if (perkiraan == null) perkiraan = new Perkiraan();
        textKodeKas.setText(perkiraan.getKode());
        textNamaKas.setText(perkiraan.getNama());
    }//GEN-LAST:event_buttonPerkiraanFind1ActionPerformed

    private void buttonPerkiraanFind2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerkiraanFind2ActionPerformed
        // TODO add your handling code here:
        perkiraanData.show();
        Perkiraan perkiraan = perkiraanData.getDataSelection();
        if (perkiraan == null) perkiraan = new Perkiraan();        
        textKodePenerimaan.setText(perkiraan.getKode());
        textNamaPenerimaan.setText(perkiraan.getNama());
    }//GEN-LAST:event_buttonPerkiraanFind2ActionPerformed

    private void buttonSisipkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSisipkanActionPerformed
        // TODO add your handling code here:
        Perkiraan perkiraan = perkiraanData.getDataSelection();        
        
        KasKeluarDetail kasKeluarDetail = new KasKeluarDetail();
        kasKeluarDetail.setKode_rekening(textKodePenerimaan.getText());
        kasKeluarDetail.setJumlah(Integer.parseInt(textJumlah.getValue().toString()));
        kasKeluarDetail.setHeader_nomor(textNomor.getText());
        kasKeluarDetail.setPerkiraan(perkiraan);
               
        
        Vector<KasKeluarDetail> kasKeluarDetails = kasKeluarDetailTableModel.getData();
        boolean baru = true;
                
        for (KasKeluarDetail kasKeluarDetailOld : kasKeluarDetails) {
            if (kasKeluarDetailOld.getKode_rekening().equals(textKodePenerimaan.getText())) {
                baru = false;
                kasKeluarDetailOld.setJumlah(kasKeluarDetailOld.getJumlah() + Integer.parseInt(textJumlah.getValue().toString()));
                break;
            }
        }        
        
        if (baru) kasKeluarDetailTableModel.getData().add(kasKeluarDetail);
        kasKeluarDetailTableModel.fireTableDataChanged();
        
        textKodePenerimaan.setText(null);
        textNamaPenerimaan.setText(null);
        textJumlah.setValue(0);
        textTotal.setValue(getTotal());
    }//GEN-LAST:event_buttonSisipkanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int index = tabelPengeluaran.getSelectedRow();
        if(index < 0){
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
        }else{            
            kasKeluarDetailTableModel.getData().remove(tabelPengeluaran.convertRowIndexToModel(index));
            kasKeluarDetailTableModel.fireTableDataChanged();
            
            textKodePenerimaan.setText(null);
            textNamaPenerimaan.setText(null);
            textJumlah.setValue(0);
            textTotal.setValue(getTotal());
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:         
        try {
            connection.setAutoCommit(false);
            KasKeluar kasKeluar = new KasKeluar();
            kasKeluar.setNomor(textNomor.getText());
            kasKeluar.setTanggal((Date) textTanggal.getValue());
            kasKeluar.setKeterangan(textKeterangan.getText());
            kasKeluar.setKode_rekening_kas(textKodeKas.getText());
            kasKeluar.setTotal(Integer.parseInt(textTotal.getValue().toString()));
            kasKeluarModel.insert(kasKeluar);
            
            //jurnal debet
            JurnalTransaksi jurnalDebet = new JurnalTransaksi();
            jurnalDebet.setTanggal(kasKeluar.getTanggal());
            jurnalDebet.setNomor_bukti(kasKeluar.getNomor());
            jurnalDebet.setKeterangan(kasKeluar.getKeterangan());
            jurnalDebet.setKode_rekening(kasKeluar.getKode_rekening_kas());
            jurnalDebet.setTipe("JKM");
            jurnalDebet.setDebet(kasKeluar.getTotal());
            jurnalDebet.setKredit(0);
            jurnalTransaksiModel.insert(jurnalDebet); 
            
            
            for (KasKeluarDetail dataTable : kasKeluarDetailTableModel.getData()) {
                kasKeluarDetailModel.insert(dataTable);
                
                //jurnal kredit
                JurnalTransaksi jurnalKredit = new JurnalTransaksi();
                jurnalKredit.setTanggal(kasKeluar.getTanggal());
                jurnalKredit.setNomor_bukti(kasKeluar.getNomor());
                jurnalKredit.setKeterangan(kasKeluar.getKeterangan());
                jurnalKredit.setKode_rekening(dataTable.getKode_rekening());
                jurnalKredit.setTipe("JKM");
                jurnalKredit.setDebet(0);
                jurnalKredit.setKredit(dataTable.getJumlah());
                jurnalTransaksiModel.insert(jurnalKredit); 
            }
            
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan!", "INFORMASI", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(KasKeluarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaruActionPerformed
        // TODO add your handling code here:
        textKodeKas.setText(null);
        textNamaKas.setText(null);
        textNomor.setText(kasKeluarModel.getNewNomor());
        textTanggal.setValue(new Date());
        textKeterangan.setText(null);

        textKodePenerimaan.setText(null);
        textNamaPenerimaan.setText(null);
        textJumlah.setValue(0);

        kasKeluarDetailTableModel.getData().removeAllElements();
        kasKeluarDetailTableModel.fireTableDataChanged();

        textTotal.setValue(getTotal());
    }//GEN-LAST:event_buttonBaruActionPerformed

    private void tabelPengeluaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelPengeluaranKeyReleased
        // TODO add your handling code here:
        tabelPengeluaranMouseClicked(null);
    }//GEN-LAST:event_tabelPengeluaranKeyReleased

    private void tabelPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengeluaranMouseClicked
        // TODO add your handling code here:
        int index = tabelPengeluaran.getSelectedRow();
        KasKeluarDetail kasKeluarDetail = kasKeluarDetailTableModel.getData().get(tabelPengeluaran.convertRowIndexToModel(index));
        textKodePenerimaan.setText(kasKeluarDetail.getKode_rekening());
        textNamaPenerimaan.setText(kasKeluarDetail.getPerkiraan().getNama());
        textJumlah.setValue(kasKeluarDetail.getJumlah());
    }//GEN-LAST:event_tabelPengeluaranMouseClicked

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        HashMap parameter = new HashMap();
        Vector<HashMap> dataDetail = new Vector<HashMap>();
        
        int i = 1;
        for(KasKeluarDetail entity : kasKeluarDetailTableModel.getData()){
            HashMap row = new HashMap();
            
            row.put("nomor", textNomor.getText());
            row.put("tanggal", (Date) textTanggal.getValue());
            
            row.put("detail_nomor", i++);
            row.put("kode_akun", entity.getKode_rekening());
            row.put("nama_akun", entity.getPerkiraan().getNama());
            row.put("keterangan", textKeterangan.getText());
            row.put("jumlah", entity.getJumlah());
            row.put("total", Integer.parseInt(textTotal.getValue().toString()));
            row.put("paramTerbilang", textTotal.getText());
            dataDetail.add(row);
        }
        JRDataSource dataSource = new JRBeanCollectionDataSource(dataDetail);
        try{
            InputStream KasKeluarLaporanJasper = getClass().getResourceAsStream("KasKeluarLaporan.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(KasKeluarLaporanJasper, parameter, dataSource);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(KasKeluarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCetakActionPerformed

    private void textKodeKasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKodeKasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKodeKasActionPerformed

    private void textTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTotalKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_textTotalKeyReleased

    private void textTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalActionPerformed

    private void textTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainMenu frame = new MainMenu();
        KasKeluarForm form = new KasKeluarForm(frame);
        frame.setVisible(true);
        frame.desktopPane.add(form);
        form.setVisible(true);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBaru;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonPerkiraanFind1;
    private javax.swing.JButton buttonPerkiraanFind2;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonSisipkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPengeluaran;
    private javax.swing.JFormattedTextField textJumlah;
    private javax.swing.JTextField textKeterangan;
    private javax.swing.JTextField textKodeKas;
    private javax.swing.JTextField textKodePenerimaan;
    private javax.swing.JTextField textNamaKas;
    private javax.swing.JTextField textNamaPenerimaan;
    private javax.swing.JTextField textNomor;
    private javax.swing.JSpinner textTanggal;
    private javax.swing.JFormattedTextField textTotal;
    // End of variables declaration//GEN-END:variables
}
