/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_akuntansi.view;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static sistem_akuntansi.view.MainMenu.Laporan;
import static sistem_akuntansi.view.MainMenu.File;
import static sistem_akuntansi.view.MainMenu.Kas;
import static sistem_akuntansi.view.MainMenu.LaporanDataObat;
import static sistem_akuntansi.view.MainMenu.LaporanPembelian;
import static sistem_akuntansi.view.MainMenu.LaporanPenjualan;
import static sistem_akuntansi.view.MainMenu.LaporanReturn;
import static sistem_akuntansi.view.MainMenu.Pelanggan;
import static sistem_akuntansi.view.MainMenu.Transaksi;
import static sistem_akuntansi.view.MainMenu.dataObat;
import static sistem_akuntansi.view.MainMenu.jenisObat;
import static sistem_akuntansi.view.MainMenu.kasKeluar;
import static sistem_akuntansi.view.MainMenu.kasMasuk;
import static sistem_akuntansi.view.MainMenu.pbf;
import static sistem_akuntansi.view.MainMenu.pembelian;
import static sistem_akuntansi.view.MainMenu.penjualan;
import static sistem_akuntansi.view.MainMenu.rekeningPerkiraan;
import static sistem_akuntansi.view.MainMenu.returnPembelian;
/**
 *
 * @author VELIK
 */
public class MainMenuLogin extends javax.swing.JFrame {

    MainMenu a;
    /**
     * Creates new form MainMenuLogin
     */
    public MainMenuLogin() {
        initComponents();
        
        a = new MainMenu();
        a.setVisible(false);
    }
    void bersih(){
        textUsername.setText("username");
        textPassword.setText("password");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboBoxUser = new javax.swing.JComboBox<>();
        registrasi = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/user.jpg.png"))); // NOI18N
        jLabel1.setText("Sign In");

        username.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        username.setText("Username");

        textUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textUsernameFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Password");

        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/ikon+login.jpg"))); // NOI18N
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Jabatan");

        comboBoxUser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboBoxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Bagian", "APA", "AA", "Kasir" }));

        registrasi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        registrasi.setText("Sign Up");
        registrasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrasiMouseClicked(evt);
            }
        });

        textPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registrasi)
                            .addComponent(jLabel3)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textUsername)
                            .addComponent(jLabel2)
                            .addComponent(comboBoxUser, 0, 268, Short.MAX_VALUE)
                            .addComponent(buttonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrasi)
                .addGap(0, 173, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUsernameFocusGained
        // TODO add your handling code here:
        String username= textUsername.getText();
        if(username.equals("username")){
            textUsername.setText("");
        }
    }//GEN-LAST:event_textUsernameFocusGained

    private void textUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUsernameFocusLost
        // TODO add your handling code here:
        String username= textUsername.getText();
        if(username.equals("")||username.equals("username") ){
            textUsername.setText("username");
            
        }
    }//GEN-LAST:event_textUsernameFocusLost

    private void textPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPasswordFocusGained
        // TODO add your handling code here:
        String password= textPassword.getText();
        if(password.equals("password")){
            textPassword.setText("");
            
        }
    }//GEN-LAST:event_textPasswordFocusGained

    private void textPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPasswordFocusLost
        // TODO add your handling code here:
        String password= textPassword.getText();
        if(password.equals("")||password.equals("password") ){
            textPassword.setText("password");
            
        }
    }//GEN-LAST:event_textPasswordFocusLost

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        try {
            Connection factory = DriverManager.getConnection("jdbc:mysql://localhost:3306/apotek_mulyo","root","");
            Statement stat = factory.createStatement();
            ResultSet rs = stat.executeQuery("select * from ms_pengguna where username='"+textUsername.getText()+"' "+"and password='"+textPassword.getText()
            +"' and level ='"+comboBoxUser.getSelectedItem()+"'");
            
            rs.last();
            if(textUsername.getText().equals("username") && textPassword.getText().equals("password") && comboBoxUser.getSelectedItem().equals("level")) {
                
             a.setVisible(true);
             //file
             File.setEnabled(true);
             dataObat.setEnabled(true);
             jenisObat.setEnabled(true);
             pbf.setEnabled(true);
             Pelanggan.setEnabled(true);
             rekeningPerkiraan.setEnabled(true);
             //transaksi
             Transaksi.setEnabled(true);
             penjualan.setEnabled(true);
             pembelian.setEnabled(true);
             returnPembelian.setEnabled(true);
             //kas
             Kas.setEnabled(true);
             kasMasuk.setEnabled(true);
             kasKeluar.setEnabled(true);
             //laporan
             Laporan.setEnabled(true);
             LaporanDataObat.setEnabled(true);
             LaporanPenjualan.setEnabled(true);
             LaporanPembelian.setEnabled(true);
             LaporanReturn.setEnabled(true);
             //field login
             textUsername.setText("");
             textPassword.setText("");
             comboBoxUser.setSelectedItem("APA");
             this.dispose();
            //Apoteker Penanggung jawab apotek
            }else if(rs.getRow()>=1){
                if(comboBoxUser.getSelectedItem().equals("APA")){
                    a.setVisible(true);
                    //file
                     File.setEnabled(true);
                     dataObat.setEnabled(true);
                     jenisObat.setEnabled(true);
                     pbf.setEnabled(true);
                     Pelanggan.setEnabled(true);
                     rekeningPerkiraan.setEnabled(true);
                     //transaksi
                     Transaksi.setEnabled(true);
                     penjualan.setEnabled(true);
                     pembelian.setEnabled(true);
                     returnPembelian.setEnabled(true);
                     //kas
                     Kas.setEnabled(true);
                     kasMasuk.setEnabled(true);
                     kasKeluar.setEnabled(true);
                     //laporan
                     Laporan.setEnabled(true);
                     LaporanDataObat.setEnabled(true);
                     LaporanPenjualan.setEnabled(true);
                     LaporanPembelian.setEnabled(true);
                     LaporanReturn.setEnabled(true);
                     //field login
                    textUsername.setText("");
                    textPassword.setText("");
                    comboBoxUser.setSelectedItem("APA");
                    this.dispose();
                     
                     //Asisten Apoteker
                     
                }else if(comboBoxUser.getSelectedItem().equals("AA")){
                    a.setVisible(true);
                    //file
                     File.setEnabled(true);
                     dataObat.setEnabled(true);
                     jenisObat.setEnabled(true);
                     pbf.setEnabled(true);
                     Pelanggan.setEnabled(true);
                     rekeningPerkiraan.setEnabled(true);
                     //transaksi
                     Transaksi.setEnabled(true);
                     penjualan.setEnabled(true);
                     pembelian.setEnabled(true);
                     returnPembelian.setEnabled(true);
                     //kas
                     Kas.setEnabled(true);
                     kasMasuk.setEnabled(true);
                     kasKeluar.setEnabled(true);
                     //laporan
                     Laporan.setEnabled(true);
                     LaporanDataObat.setEnabled(true);
                     LaporanPenjualan.setEnabled(true);
                     LaporanPembelian.setEnabled(true);
                     LaporanReturn.setEnabled(true);
                     //field login
                    textUsername.setText("");
                    textPassword.setText("");
                    comboBoxUser.setSelectedItem("AA");
                    this.dispose();
                     
                     //kasir
                }else if(comboBoxUser.getSelectedItem().equals("Kasir")){
                    a.setVisible(true);
                    //file
                     File.setEnabled(false);
                     dataObat.setEnabled(false);
                     jenisObat.setEnabled(false);
                     pbf.setEnabled(false);
                     Pelanggan.setEnabled(true);
                     rekeningPerkiraan.setEnabled(true);
                     //transaksi
                     Transaksi.setEnabled(true);
                     penjualan.setEnabled(true);
                     pembelian.setEnabled(true);
                     returnPembelian.setEnabled(true);
                     //kas
                     Kas.setEnabled(true);
                     kasMasuk.setEnabled(true);
                     kasKeluar.setEnabled(true);
                     //laporan
                     Laporan.setEnabled(false);
                     LaporanDataObat.setEnabled(false);
                     LaporanPenjualan.setEnabled(false);
                     LaporanPembelian.setEnabled(false);
                     LaporanReturn.setEnabled(false);
                     //field login
                    textUsername.setText("");
                    textPassword.setText("");
                    comboBoxUser.setSelectedItem("Kasir");
                    this.dispose();   
                    
                }else if ((rs.getRow()==0)){
                    JOptionPane.showMessageDialog(null, "maaf login gagal , periksa kembali username dan password");
                        //file
                     File.setEnabled(false);
                     dataObat.setEnabled(false);
                     jenisObat.setEnabled(false);
                     pbf.setEnabled(false);
                     Pelanggan.setEnabled(false);
                     rekeningPerkiraan.setEnabled(false);
                     //transaksi
                     Transaksi.setEnabled(false);
                     penjualan.setEnabled(false);
                     pembelian.setEnabled(false);
                     returnPembelian.setEnabled(false);
                     //kas
                     Kas.setEnabled(false);
                     kasMasuk.setEnabled(false);
                     kasKeluar.setEnabled(false);
                     //laporan
                     Laporan.setEnabled(false);
                     LaporanDataObat.setEnabled(false);
                     LaporanPenjualan.setEnabled(false);
                     LaporanPembelian.setEnabled(false);
                     LaporanReturn.setEnabled(false);
                }   
                
                stat.close();
            }
        }catch(SQLException e) {
            System.out.print("Eror" +e);
            
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void registrasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrasiMouseClicked
        // TODO add your handling code here:
        new PenggunaForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JComboBox<String> comboBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel registrasi;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
