/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_akuntansi.view;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import sistem_akuntansi.Factory;
/**
 *
 * @author arochman.aryanta
 */
public class MainMenu extends javax.swing.JFrame {

    private PerkiraanForm perkiraanForm;
    private BarangForm barangForm;
    private JenisForm jenisForm;
    private KasKeluarForm kasKeluarForm;
    private KasMasukForm kasMasukForm;
    private PbfForm pbfForm;
    private PelangganForm pelangganForm;
    private PenjualanForm penjualanForm;
    private PembelianForm pembelianForm;
    private ReturnForm returnForm;
    
    //private BarangData barangData;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        
     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        perkiraanForm = new PerkiraanForm(this);
        barangForm = new BarangForm(this);
        jenisForm = new JenisForm(this);
        pbfForm = new PbfForm(this);
        pelangganForm = new PelangganForm(this);
        kasMasukForm = new KasMasukForm(this);
        kasKeluarForm = new KasKeluarForm(this);
        penjualanForm = new PenjualanForm(this);
        pembelianForm = new PembelianForm(this);
        returnForm = new ReturnForm(this);
        
        //barangData = new BarangData(this);
        
        
        desktopPane.add(perkiraanForm);
        desktopPane.add(barangForm);
        desktopPane.add(jenisForm);
        desktopPane.add(pbfForm);
        desktopPane.add(pelangganForm);
        desktopPane.add(kasMasukForm);
        desktopPane.add(kasKeluarForm);
        desktopPane.add(penjualanForm);
        desktopPane.add(pembelianForm);
        desktopPane.add(returnForm);
        
       // desktopPane.add(barangData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Exit = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Akuntansi");

        desktopPane.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        desktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desktopPaneMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/Logo Apotek Mulyo Potong.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("APOTEK MULYO BANDAR");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI AKUNTANSI PENJUALAN & PEMBELIAN");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 51));
        jLabel4.setText("Jl. Raya Wonokerto Bandar Batang");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/ikon obat.png"))); // NOI18N

        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))))
                .addContainerGap())
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(desktopPaneLayout.createSequentialGroup()
                            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        File.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/ikon file.jpg"))); // NOI18N
        File.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        dataObat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        dataObat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        dataObat.setText("Data Obat");
        dataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataObatActionPerformed(evt);
            }
        });
        File.add(dataObat);

        jenisObat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jenisObat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jenisObat.setText("Jenis Obat");
        jenisObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisObatActionPerformed(evt);
            }
        });
        File.add(jenisObat);

        pbf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        pbf.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pbf.setText("Pedagang Besar Farmasi");
        pbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbfActionPerformed(evt);
            }
        });
        File.add(pbf);

        Pelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Pelanggan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pelanggan.setText("Pelanggan");
        Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganActionPerformed(evt);
            }
        });
        File.add(Pelanggan);

        rekeningPerkiraan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        rekeningPerkiraan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rekeningPerkiraan.setText("Rekening Pekiraan");
        rekeningPerkiraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekeningPerkiraanActionPerformed(evt);
            }
        });
        File.add(rekeningPerkiraan);

        jMenuBar1.add(File);

        Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/transaksi.jpg"))); // NOI18N
        Transaksi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });

        penjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        penjualan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        penjualan.setText("Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        Transaksi.add(penjualan);

        pembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        pembelian.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pembelian.setText("Pembelian");
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        Transaksi.add(pembelian);

        returnPembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        returnPembelian.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        returnPembelian.setText("Return Pembelian");
        returnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnPembelianActionPerformed(evt);
            }
        });
        Transaksi.add(returnPembelian);

        jMenuBar1.add(Transaksi);

        Kas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/kas.jpg"))); // NOI18N
        Kas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        kasMasuk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        kasMasuk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kasMasuk.setText("Kas Masuk");
        kasMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasMasukActionPerformed(evt);
            }
        });
        Kas.add(kasMasuk);

        kasKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        kasKeluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kasKeluar.setText("Kas Keluar");
        kasKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasKeluarActionPerformed(evt);
            }
        });
        Kas.add(kasKeluar);

        jMenuBar1.add(Kas);

        Laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/laporan.jpg"))); // NOI18N
        Laporan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanActionPerformed(evt);
            }
        });

        LaporanDataObat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        LaporanDataObat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanDataObat.setText("Laporan Data Obat");
        LaporanDataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanDataObatActionPerformed(evt);
            }
        });
        Laporan.add(LaporanDataObat);

        LaporanPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        LaporanPenjualan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanPenjualan.setText("Laporan Penjualan");
        LaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPenjualanActionPerformed(evt);
            }
        });
        Laporan.add(LaporanPenjualan);

        LaporanPembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        LaporanPembelian.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanPembelian.setText("Laporan Pembelian");
        LaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPembelianActionPerformed(evt);
            }
        });
        Laporan.add(LaporanPembelian);

        LaporanReturn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        LaporanReturn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanReturn.setText("Laporan Return");
        LaporanReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanReturnActionPerformed(evt);
            }
        });
        Laporan.add(LaporanReturn);

        JurnalTransaksiUmum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        JurnalTransaksiUmum.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JurnalTransaksiUmum.setText("Laporan Jurnal Umum");
        JurnalTransaksiUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JurnalTransaksiUmumActionPerformed(evt);
            }
        });
        Laporan.add(JurnalTransaksiUmum);

        LaporanMutasiObat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        LaporanMutasiObat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanMutasiObat.setText("Laporan Mutasi Obat");
        LaporanMutasiObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanMutasiObatActionPerformed(evt);
            }
        });
        Laporan.add(LaporanMutasiObat);

        jMenuBar1.add(Laporan);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/exit.jpg"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.add(jSeparator1);

        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kasMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasMasukActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            kasMasukForm.show();
            kasMasukForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kasMasukActionPerformed

    private void jenisObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisObatActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            jenisForm.show();
            jenisForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jenisObatActionPerformed

    private void pbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbfActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            pbfForm.show();
            pbfForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pbfActionPerformed

    private void PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelangganActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            pelangganForm.show();
            pelangganForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PelangganActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            pembelianForm.show();
            pembelianForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pembelianActionPerformed

    private void kasKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasKeluarActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            kasKeluarForm.show();
            kasKeluarForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kasKeluarActionPerformed

    private void rekeningPerkiraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekeningPerkiraanActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            perkiraanForm.show();
            perkiraanForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rekeningPerkiraanActionPerformed

    private void dataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataObatActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            barangForm.show();
            barangForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dataObatActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransaksiActionPerformed

    private void returnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnPembelianActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            returnForm.show();
            returnForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_returnPembelianActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            penjualanForm.show();
            penjualanForm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_penjualanActionPerformed

    private void desktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopPaneMouseClicked

    }//GEN-LAST:event_desktopPaneMouseClicked

    private void LaporanDataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanDataObatActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("BarangLaporan.jasper"), null, Factory.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LaporanDataObatActionPerformed

    private void LaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPenjualanActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("PenjualanLaporan.jasper"), null, Factory.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LaporanPenjualanActionPerformed

    private void LaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPembelianActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("PembelianLaporan.jasper"), null, Factory.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LaporanPembelianActionPerformed

    private void LaporanReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanReturnActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("ReturnLaporanForm.jasper"), null, Factory.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LaporanReturnActionPerformed

    private void LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaporanActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        new MainMenuLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void JurnalTransaksiUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JurnalTransaksiUmumActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("JurnalTransaksiUmum.jasper"), null, Factory.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_JurnalTransaksiUmumActionPerformed

    private void LaporanMutasiObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanMutasiObatActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("MutasiObatLaporan.jasper"), null, Factory.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LaporanMutasiObatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Exit;
    public static final javax.swing.JMenu File = new javax.swing.JMenu();
    public static final javax.swing.JMenuItem JurnalTransaksiUmum = new javax.swing.JMenuItem();
    public static final javax.swing.JMenu Kas = new javax.swing.JMenu();
    public static final javax.swing.JMenu Laporan = new javax.swing.JMenu();
    public static final javax.swing.JMenuItem LaporanDataObat = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem LaporanMutasiObat = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem LaporanPembelian = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem LaporanPenjualan = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem LaporanReturn = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem Pelanggan = new javax.swing.JMenuItem();
    public static final javax.swing.JMenu Transaksi = new javax.swing.JMenu();
    public static final javax.swing.JMenuItem dataObat = new javax.swing.JMenuItem();
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static final javax.swing.JMenuItem jenisObat = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem kasKeluar = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem kasMasuk = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem pbf = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem pembelian = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem penjualan = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem rekeningPerkiraan = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem returnPembelian = new javax.swing.JMenuItem();
    // End of variables declaration//GEN-END:variables
}
