/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_akuntansi.view;


import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import sistem_akuntansi.Factory;
import sistem_akuntansi.entity.Barang;
import sistem_akuntansi.entity.JurnalTransaksi;
import sistem_akuntansi.entity.MutasiObat;
import sistem_akuntansi.entity.PembelianDetail;
import sistem_akuntansi.entity.Pbf;
import sistem_akuntansi.entity.Pembelian;
import sistem_akuntansi.model.JurnalTransaksiModel;
import sistem_akuntansi.model.MutasiObatModel;
import sistem_akuntansi.model.PembelianDetailModel;
import sistem_akuntansi.model.PembelianDetailTableModel;
import sistem_akuntansi.model.PembelianModel;
/**
 *
 * @author VELIK
 */
public class PembelianForm extends javax.swing.JInternalFrame {
    
    private Connection connection;
    private PbfData pbfData;
    private BarangData barangData;
    private PembelianDetailTableModel pembelianDetailTableModel;
    
    private final PembelianModel pembelianModel;
    private final PembelianDetailModel pembelianDetailModel;
    private final JurnalTransaksiModel jurnalTransaksiModel;
    private final MutasiObatModel mutasiObatModel; 
    
    public PembelianForm(MainMenu main) {
        initComponents();
        connection = Factory.getConnection();
        
        pbfData = new PbfData(main, true);
        pbfData.setLocationRelativeTo(this);
        barangData = new BarangData(main, true);
        barangData.setLocationRelativeTo(this);
        pembelianDetailTableModel = new PembelianDetailTableModel(new Vector<PembelianDetail>());
        tabelPembelianDetail.setModel(pembelianDetailTableModel);
        
        pembelianModel = new PembelianModel(connection);
        pembelianDetailModel = new PembelianDetailModel(connection);
        jurnalTransaksiModel = new JurnalTransaksiModel(connection);
        mutasiObatModel = new MutasiObatModel(connection);
        
        restructureTable();
       //buttonBaruActionPerformed(null);
    }
    
    private void restructureTable(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tabelPembelianDetail.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        tabelPembelianDetail.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        tabelPembelianDetail.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tabelPembelianDetail.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabelPembelianDetail.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelPembelianDetail.getColumnModel().getColumn(2).setPreferredWidth(80);
        tabelPembelianDetail.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabelPembelianDetail.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabelPembelianDetail.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabelPembelianDetail.getColumnModel().getColumn(6).setPreferredWidth(100);
    }
    private Integer getJumlah() {
        Integer qty = Integer.parseInt(textKuantiti.getValue().toString());
        Integer harga = Integer.parseInt(textHargaBeli.getValue().toString());
        Integer jumlah = qty * harga;
        return jumlah;
    }

    public Integer getTotal() {
        Integer total = 0;
        for (PembelianDetail pembelianDetail : pembelianDetailTableModel.getData()) {
            total = total + pembelianDetail.getJumlah();
        }
        return total;
    }

    public static void main(String args[]){
        MainMenu frame = new MainMenu();
        PembelianForm form = new PembelianForm(frame);
        frame.setVisible(true);
        frame.desktopPane.add(form);
        form.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNofaktur = new javax.swing.JTextField();
        textKodePbf = new javax.swing.JTextField();
        textNamaPbf = new javax.swing.JTextField();
        textTanggal = new javax.swing.JSpinner();
        buttonPbf = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textKodeObat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textKuantiti = new javax.swing.JSpinner();
        textHargaBeli = new javax.swing.JFormattedTextField();
        textJumlah = new javax.swing.JFormattedTextField();
        buttonSisipkan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembelianDetail = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        textTotal = new javax.swing.JFormattedTextField();
        buttonBaru = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        textNamaObat = new javax.swing.JTextField();
        buttonObat = new javax.swing.JButton();
        textExpDate = new javax.swing.JSpinner();
        buttonCetak = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FORM PEMBELIAN");

        jLabel1.setText("PBF");

        jLabel2.setText("Nofaktur");

        jLabel3.setText("Tanggal");

        textNofaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNofakturActionPerformed(evt);
            }
        });

        textKodePbf.setEnabled(false);

        textNamaPbf.setEnabled(false);
        textNamaPbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaPbfActionPerformed(evt);
            }
        });

        textTanggal.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        textTanggal.setEditor(new javax.swing.JSpinner.DateEditor(textTanggal, "dd/MM/YYYY"));

        buttonPbf.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonPbf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonPbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPbfActionPerformed(evt);
            }
        });

        jLabel4.setText("EXP. Date");

        jLabel5.setText("Input Data Obat");

        jLabel6.setText("Kode Obat");

        textKodeObat.setEnabled(false);
        textKodeObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKodeObatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Kuantiti");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Harga");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Jumlah");

        textKuantiti.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        textKuantiti.setEditor(new javax.swing.JSpinner.NumberEditor(textKuantiti, "#,##0"));
        textKuantiti.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                textKuantitiStateChanged(evt);
            }
        });

        textHargaBeli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textHargaBeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textHargaBeli.setValue(0);

        textJumlah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textJumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textJumlah.setValue(0);

        buttonSisipkan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonSisipkan.setText("SISIPKAN");
        buttonSisipkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSisipkanActionPerformed(evt);
            }
        });

        buttonHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        tabelPembelianDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPembelianDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembelianDetailMouseClicked(evt);
            }
        });
        tabelPembelianDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelPembelianDetailKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPembelianDetail);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("TOTAL");

        textTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTotal.setEnabled(false);
        textTotal.setValue(0);

        buttonBaru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonBaru.setText("BARU");
        buttonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaruActionPerformed(evt);
            }
        });

        buttonSimpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        textNamaObat.setEnabled(false);

        buttonObat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonObatActionPerformed(evt);
            }
        });

        textExpDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        textExpDate.setEditor(new javax.swing.JSpinner.DateEditor(textExpDate, "dd/MM/yyyy"));

        buttonCetak.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonCetak.setText("CETAK");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 295, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textKodeObat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textKodePbf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textNofaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNamaObat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(textNamaPbf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonPbf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonObat, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textKuantiti, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSisipkan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonHapus))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(buttonCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textKodePbf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNamaPbf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPbf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNofaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(buttonObat))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKuantiti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSisipkan)
                    .addComponent(buttonHapus)
                    .addComponent(textExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBaru)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonCetak))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textKodeObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKodeObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKodeObatActionPerformed

    private void textNamaPbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaPbfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaPbfActionPerformed

    private void buttonPbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPbfActionPerformed
        // TODO add your handling code here:
        pbfData.show();
        Pbf pbf = pbfData.getDataSelection();
        if (pbf == null) {
            pbf = new Pbf();
        }
        textKodePbf.setText(pbf.getKode_pbf());
        textNamaPbf.setText(pbf.getNama_pbf());
        
    }//GEN-LAST:event_buttonPbfActionPerformed

    private void textNofakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNofakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNofakturActionPerformed

    private void buttonSisipkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSisipkanActionPerformed
        // TODO add your handling code here:
         Pbf pbf = pbfData.getDataSelection();
         Barang barang = barangData.getDataSelection();
         PembelianDetail pembelianDetail = new PembelianDetail();
         
         pembelianDetail.setKode_obat(textKodeObat.getText());
         pembelianDetail.setKuantiti(Integer.parseInt(textKuantiti.getValue().toString()));
         pembelianDetail.setHarga(Integer.parseInt(textHargaBeli.getValue().toString()));
         pembelianDetail.setJumlah(Integer.parseInt(textJumlah.getValue().toString()));
         pembelianDetail.setExp_date((Date)textExpDate.getValue());
         pembelianDetail.setHeader_nofaktur(textNofaktur.getText());
         pembelianDetail.setBarang(barang);
         //pembelianDetail.setPbf(pbf);
        // penjualanDetail.setJenis(jenis);
         Vector<PembelianDetail> pembelianDetails = pembelianDetailTableModel.getData();
         boolean baru = true;
         
         for (PembelianDetail pembelianDetailOld : pembelianDetails) {
            if (pembelianDetailOld.getKode_obat().equals(textKodeObat.getText())) {
                baru = false;
                pembelianDetailOld.setKuantiti(pembelianDetailOld.getKuantiti() + Integer.parseInt(textKuantiti.getValue().toString()));
                pembelianDetailOld.setJumlah(pembelianDetailOld.getJumlah() + Integer.parseInt(textJumlah.getValue().toString()));
                break;
            }
         }
         if (baru) {
            pembelianDetailTableModel.getData().add(pembelianDetail);
        }
        pembelianDetailTableModel.fireTableDataChanged();

        textKodeObat.setText(null);
        textNamaObat.setText(null);
        textExpDate.setValue(new Date());
        textKuantiti.setValue(0);
        textHargaBeli.setValue(0);
        textJumlah.setValue(0);
        textTotal.setValue(getTotal());
    }//GEN-LAST:event_buttonSisipkanActionPerformed

    private void buttonObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonObatActionPerformed
        // TODO add your handling code here:
         barangData.show();
        Barang barang = barangData.getDataSelection();
        if (barang == null) {
            barang = new Barang();
        }
        textKodeObat.setText(barang.getKode_obat());
        textNamaObat.setText(barang.getNama_obat());
        textExpDate.setValue(new Date());
        textKuantiti.setValue(1);
        textHargaBeli.setValue(barang.getHarga_beli());
        textJumlah.setValue(getJumlah());
    }//GEN-LAST:event_buttonObatActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
         int index = tabelPembelianDetail.getSelectedRow();
         if(index < 0) {
         JOptionPane.showMessageDialog(this, "Pilih data dahulu", "peringatan", JOptionPane.WARNING_MESSAGE);
         }else{
            pembelianDetailTableModel.getData().remove(tabelPembelianDetail.convertRowIndexToModel(index));
            pembelianDetailTableModel.fireTableDataChanged();
            
            textKodeObat.setText(null);
            textNamaObat.setText(null);
            textExpDate.setValue(new Date());
            textJumlah.setValue(0);
            textTotal.setValue(getTotal());
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaruActionPerformed
        // TODO add your handling code here:
        textKodePbf.setText(null);
        textNamaPbf.setText(null);
        textNofaktur.setText(null);
        textTanggal.setValue(new Date());
        textKodeObat.setText(null);
        textNamaObat.setText(null);
        textExpDate.setValue(new Date());
        textJumlah.setValue(0);
        
        pembelianDetailTableModel.getData().removeAllElements();
        pembelianDetailTableModel.fireTableDataChanged();
        textJumlah.setValue(0);
         
         pembelianDetailTableModel.getData().removeAllElements();
         pembelianDetailTableModel.fireTableDataChanged();
         textTotal.setValue(getTotal());
    }//GEN-LAST:event_buttonBaruActionPerformed

    private void textKuantitiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_textKuantitiStateChanged
        // TODO add your handling code here:
        textJumlah.setValue(getJumlah());
    }//GEN-LAST:event_textKuantitiStateChanged

    private void tabelPembelianDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembelianDetailMouseClicked
        // TODO add your handling code here:
         int index = tabelPembelianDetail.getSelectedRow();
        PembelianDetail pembelianDetail = pembelianDetailTableModel.getData().get(tabelPembelianDetail.convertRowIndexToModel(index));
        
        textKodeObat.setText(pembelianDetail.getKode_obat());
        textExpDate.setValue(pembelianDetail.getExp_date());
        textKuantiti.setValue(pembelianDetail.getKuantiti());
        textHargaBeli.setValue(pembelianDetail.getHarga());
        textJumlah.setValue(pembelianDetail.getJumlah());
        textJumlah.setValue(pembelianDetail.getJumlah());
    }//GEN-LAST:event_tabelPembelianDetailMouseClicked

    private void tabelPembelianDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelPembelianDetailKeyReleased
        // TODO add your handling code here:
         tabelPembelianDetailMouseClicked(null);
    }//GEN-LAST:event_tabelPembelianDetailKeyReleased

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            Pembelian pembelian = new Pembelian();
            pembelian.setNofaktur(textNofaktur.getText());
            pembelian.setTanggal((Date)textTanggal.getValue());
            
            pembelian.setKode_pbf(textKodePbf.getText());
            pembelian.setTotal(Integer.parseInt(textTotal.getValue().toString()));
            pembelianModel.insert(pembelian);
            
            //jurnal debet
            JurnalTransaksi jurnalDebet = new JurnalTransaksi();
            jurnalDebet.setTanggal(pembelian.getTanggal());
            jurnalDebet.setNomor_bukti(pembelian.getNofaktur());
            jurnalDebet.setKeterangan("Pembelian");
            jurnalDebet.setKode_rekening("1-1100");
            jurnalDebet.setTipe("JKM");
            jurnalDebet.setDebet(pembelian.getTotal());
            jurnalDebet.setKredit(0);
            jurnalTransaksiModel.insert(jurnalDebet); 
            
            for (PembelianDetail dataTable : pembelianDetailTableModel.getData()){
                pembelianDetailModel.insert(dataTable);
                
                //jurnal kredit
                JurnalTransaksi jurnalKredit = new JurnalTransaksi();
                jurnalKredit.setTanggal(pembelian.getTanggal());
                jurnalKredit.setNomor_bukti(pembelian.getNofaktur());
                jurnalKredit.setKode_rekening("1-1100");
                jurnalKredit.setKeterangan("Pembelian");
                jurnalKredit.setTipe("JKM");
                jurnalKredit.setDebet(0);
                jurnalKredit.setKredit(dataTable.getJumlah());
                jurnalTransaksiModel.insert(jurnalKredit); 
            
            
            //mutasi
            MutasiObat mutasiObat = new MutasiObat();
            mutasiObat.setTanggal(pembelian.getTanggal());
            mutasiObat.setNomor_bukti(pembelian.getNofaktur());
            mutasiObat.setKeterangan("Pembelian");
            mutasiObat.setKode_obat(dataTable.getKode_obat());
            mutasiObat.setMasuk_kuantiti(dataTable.getKuantiti());
            mutasiObat.setMasuk_jumlah(dataTable.getJumlah());
            mutasiObat.setKeluar_kuantiti(0);
            mutasiObat.setKeluar_jumlah(0);
            mutasiObatModel.insert(mutasiObat);
            
            }
            connection.commit();
            JOptionPane.showMessageDialog(this, "data berhasil disimpan", "informasi", JOptionPane.INFORMATION_MESSAGE);
            //buttonBaruActionPerformed(evt);
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "data gagal disimpan", "informasi", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(PenjualanForm.class.getName()).log(Level.SEVERE, null, ex);
            try{
                connection.rollback();
            }catch (SQLException exl) {
                Logger.getLogger(PenjualanForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        HashMap parameter = new HashMap();
        Vector<HashMap> dataDetail = new Vector<HashMap>();
        
        int i = 1;
        for(PembelianDetail entity : pembelianDetailTableModel.getData()){
            HashMap row = new HashMap();
            row.put("kode_pbf", textKodePbf.getText());
            row.put("nama_pbf", textNamaPbf.getText());
            row.put("no_faktur", textNofaktur.getText());
            row.put("tanggal", (Date) textTanggal.getValue());
            
            row.put("detail_nomor", i++);
            row.put("detail_kode_obat", entity.getKode_obat());
            row.put("detail_nama_obat", entity.getBarang().getNama_obat());
            row.put("detail_exp_date", entity.getExp_date());
            row.put("detail_kuantiti", entity.getKuantiti());
            row.put("detail_harga", entity.getHarga());
            row.put("detail_jumlah", entity.getJumlah());
            row.put("total", Integer.parseInt(textTotal.getValue().toString()));
            dataDetail.add(row);
        }
        JRDataSource dataSource = new JRBeanCollectionDataSource(dataDetail);
        try{
            InputStream PembelianFakturJasper = getClass().getResourceAsStream("PembelianFaktur.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(PembelianFakturJasper, parameter, dataSource);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(PenjualanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBaru;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonObat;
    private javax.swing.JButton buttonPbf;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonSisipkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPembelianDetail;
    private javax.swing.JSpinner textExpDate;
    private javax.swing.JFormattedTextField textHargaBeli;
    private javax.swing.JFormattedTextField textJumlah;
    private javax.swing.JTextField textKodeObat;
    private javax.swing.JTextField textKodePbf;
    private javax.swing.JSpinner textKuantiti;
    private javax.swing.JTextField textNamaObat;
    private javax.swing.JTextField textNamaPbf;
    private javax.swing.JTextField textNofaktur;
    private javax.swing.JSpinner textTanggal;
    private javax.swing.JFormattedTextField textTotal;
    // End of variables declaration//GEN-END:variables
}
