/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_akuntansi.view;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import sistem_akuntansi.Factory;
import sistem_akuntansi.entity.Barang;
import sistem_akuntansi.entity.JurnalTransaksi;
import sistem_akuntansi.entity.MutasiObat;
import sistem_akuntansi.entity.PembelianDetail;
import sistem_akuntansi.entity.Pbf;
import sistem_akuntansi.entity.Pembelian;
import sistem_akuntansi.entity.ReturnObat;
import sistem_akuntansi.entity.ReturnDetail;
import sistem_akuntansi.model.JurnalTransaksiModel;
import sistem_akuntansi.model.MutasiObatModel;
import sistem_akuntansi.model.ReturnDetailModel;
import sistem_akuntansi.model.ReturnDetailTableModel;
import sistem_akuntansi.model.ReturnModel;
/**
 *
 * @author VELIK
 */
public class ReturnForm extends javax.swing.JInternalFrame {

    private Connection connection;
    private PbfData pbfData;
    private PembelianData pembelianData;
    private PembelianDetailData pembelianDetailData;
    private ReturnDetailTableModel returnDetailTableModel;
    
    private final ReturnModel returnModel;
    private final ReturnDetailModel returnDetailModel;
    private final JurnalTransaksiModel jurnalTransaksiModel;
    private final MutasiObatModel mutasiObatModel; 
    
    public ReturnForm(MainMenu main) {
        initComponents();
        connection = Factory.getConnection();
        
        pbfData = new PbfData(main, true);
        pbfData.setLocationRelativeTo(this);
        pembelianData = new PembelianData(main, true);
        pembelianData.setLocationRelativeTo(this);
        pembelianDetailData = new PembelianDetailData(main, true);
        pembelianDetailData.setLocationRelativeTo(this);
        
        returnDetailTableModel = new ReturnDetailTableModel(new Vector<ReturnDetail>());
        tabelReturnDetail.setModel(returnDetailTableModel);
        
        returnModel = new ReturnModel(connection);
        returnDetailModel = new ReturnDetailModel(connection);
        jurnalTransaksiModel = new JurnalTransaksiModel(connection);
        mutasiObatModel = new MutasiObatModel(connection);
        
        restructureTable();
       // buttonBaruActionPerformed(null);
    }
    private void restructureTable(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tabelReturnDetail.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        
        tabelReturnDetail.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabelReturnDetail.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelReturnDetail.getColumnModel().getColumn(2).setPreferredWidth(80);
        tabelReturnDetail.getColumnModel().getColumn(3).setPreferredWidth(100);
    }
    private Integer getJumlah() {
        Integer qty = Integer.parseInt(textKuantiti.getValue().toString());
        Integer hargaBeli = Integer.parseInt(textHargaBeli.getValue().toString());
        Integer jumlah = qty * hargaBeli;
        return jumlah;
    }

    public Integer getTotal() {
        Integer total = 0;
        for (ReturnDetail returnDetail : returnDetailTableModel.getData()) {
            total = total + returnDetail.getJumlah();
        }
        return total;
    }

    public static void main(String args[]){
        MainMenu frame = new MainMenu();
        ReturnForm form = new ReturnForm(frame);
        frame.setVisible(true);
        frame.desktopPane.add(form);
        form.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textKodePbf = new javax.swing.JTextField();
        textNamaPbf = new javax.swing.JTextField();
        buttonPbfFind = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNofaktur = new javax.swing.JTextField();
        textTanggalReturn = new javax.swing.JSpinner();
        textNomorReturn = new javax.swing.JTextField();
        buttonPembelianFind = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textKodeObat = new javax.swing.JTextField();
        buttonObatFind = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textKuantiti = new javax.swing.JSpinner();
        textHargaBeli = new javax.swing.JFormattedTextField();
        textJumlah = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelReturnDetail = new javax.swing.JTable();
        buttonSisipkan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textTotal = new javax.swing.JFormattedTextField();
        buttonBaru = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        textTanggalFaktur = new javax.swing.JFormattedTextField();
        textExpDate = new javax.swing.JFormattedTextField();
        buttonCetak = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FORM RETURN PEMBELIAN");

        jLabel1.setText("PBF");

        buttonPbfFind.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        buttonPbfFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonPbfFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPbfFindActionPerformed(evt);
            }
        });

        jLabel2.setText("Nomor");

        jLabel3.setText("Tanggal Return");

        textNofaktur.setEnabled(false);

        textTanggalReturn.setModel(new javax.swing.SpinnerDateModel());
        textTanggalReturn.setEditor(new javax.swing.JSpinner.DateEditor(textTanggalReturn, "dd/MM/YYYY"));

        buttonPembelianFind.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        buttonPembelianFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonPembelianFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPembelianFindActionPerformed(evt);
            }
        });

        jLabel6.setText("Item Pembelian");

        jLabel4.setText("Detail Pembelian");

        textKodeObat.setEnabled(false);

        buttonObatFind.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        buttonObatFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem_akuntansi/img/search 15px.jpg"))); // NOI18N
        buttonObatFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonObatFindActionPerformed(evt);
            }
        });

        jLabel5.setText("Kuantiti");

        jLabel7.setText("Harga");

        jLabel8.setText("Jumlah");

        textKuantiti.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        textKuantiti.setEditor(new javax.swing.JSpinner.NumberEditor(textKuantiti, "#,##0"));
        textKuantiti.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                textKuantitiStateChanged(evt);
            }
        });

        textHargaBeli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textHargaBeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textHargaBeli.setValue(0);

        textJumlah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textJumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textJumlah.setValue(0);

        tabelReturnDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelReturnDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelReturnDetailMouseClicked(evt);
            }
        });
        tabelReturnDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelReturnDetailKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelReturnDetail);

        buttonSisipkan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonSisipkan.setText("SISIPKAN");
        buttonSisipkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSisipkanActionPerformed(evt);
            }
        });

        buttonHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("TOTAL");

        textTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        textTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTotal.setEnabled(false);
        textTotal.setValue(0);

        buttonBaru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonBaru.setText("BARU");
        buttonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaruActionPerformed(evt);
            }
        });

        buttonSimpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        textTanggalFaktur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        textTanggalFaktur.setEnabled(false);

        textExpDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        textExpDate.setEnabled(false);

        buttonCetak.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonCetak.setText("CETAK");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonObatFind, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(textNomorReturn, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textKodePbf, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textTanggalReturn)))
                                            .addComponent(textNofaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textNamaPbf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonPbfFind, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(textTanggalFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonPembelianFind, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(textKuantiti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSisipkan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHapus))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonCetak)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonBaru)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSimpan))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textKodePbf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNamaPbf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPbfFind))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textNomorReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textTanggalReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonPembelianFind)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(textNofaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textTanggalFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonObatFind)
                    .addComponent(textKuantiti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSisipkan)
                    .addComponent(buttonHapus)
                    .addComponent(textExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBaru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSimpan)
                        .addComponent(buttonCetak)))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPbfFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPbfFindActionPerformed
        // TODO add your handling code here:
        pbfData.show();
        Pbf pbf = pbfData.getDataSelection();
        if (pbf == null) {
            pbf = new Pbf();
        }
        textKodePbf.setText(pbf.getKode_pbf());
        textNamaPbf.setText(pbf.getNama_pbf());
    }//GEN-LAST:event_buttonPbfFindActionPerformed

    private void buttonPembelianFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPembelianFindActionPerformed
        // TODO add your handling code here:
        pembelianData.show();
        Pembelian pembelian = pembelianData.getDataSelection();
        if (pembelian == null) {
            pembelian = new Pembelian();
        }
        textNofaktur.setText(pembelian.getNofaktur());
        textTanggalFaktur.setValue(pembelian.getTanggal());
        
    }//GEN-LAST:event_buttonPembelianFindActionPerformed

    private void buttonObatFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonObatFindActionPerformed
        // TODO add your handling code here:
        pembelianDetailData.show();
        PembelianDetail pembelianDetail = pembelianDetailData.getDataSelection();
        if (pembelianDetail == null) {
            pembelianDetail = new PembelianDetail();
        }
        textKodeObat.setText(pembelianDetail.getKode_obat());
        textExpDate.setValue(pembelianDetail.getExp_date());
        textKuantiti.setValue(1);
        textHargaBeli.setValue(pembelianDetail.getHarga());
        textJumlah.setValue(getJumlah());
    }//GEN-LAST:event_buttonObatFindActionPerformed

    private void buttonSisipkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSisipkanActionPerformed
        // TODO add your handling code here:
        PembelianDetail pembelianDetail = pembelianDetailData.getDataSelection();
        Pbf pbf = pbfData.getDataSelection();
        Pembelian pembelian = pembelianData.getDataSelection();
        ReturnDetail returnDetail = new ReturnDetail();
        returnDetail.setKode_obat(textKodeObat.getText());

        returnDetail.setHarga(Integer.parseInt(textHargaBeli.getValue().toString()));
        returnDetail.setKuantiti(Integer.parseInt(textKuantiti.getValue().toString()));
        returnDetail.setJumlah(Integer.parseInt(textJumlah.getValue().toString()));
        returnDetail.setHeader_nomor(textNomorReturn.getText());
        returnDetail.setPembelian(pembelian);
       // returnDetail.setPembelianDetail(pembelianDetail);
        Vector<ReturnDetail> returnDetails = returnDetailTableModel.getData();
        boolean baru = true;

        for (ReturnDetail returnDetailOld : returnDetails) {
            if (returnDetailOld.getKode_obat().equals(textKodeObat.getText())) {
                baru = false;
                returnDetailOld.setKuantiti(returnDetailOld.getKuantiti() + Integer.parseInt(textKuantiti.getValue().toString()));
                returnDetailOld.setJumlah(returnDetailOld.getJumlah() + Integer.parseInt(textJumlah.getValue().toString()));
                break;
            }
        }
        if (baru) {
            returnDetailTableModel.getData().add(returnDetail);
        }
        returnDetailTableModel.fireTableDataChanged();

       
        textKodeObat.setText(null);
        
        textExpDate.setText(null);
        textTanggalReturn.setValue(new Date());
        textHargaBeli.setValue(0);
        textKuantiti.setValue(0);
        textJumlah.setValue(0);
        textTotal.setValue(getTotal());
    }//GEN-LAST:event_buttonSisipkanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int index = tabelReturnDetail.getSelectedRow();
        if(index < 0) {
        JOptionPane.showMessageDialog(this, "Pilih data dahulu", "peringatan", JOptionPane.WARNING_MESSAGE);
        }else{
            returnDetailTableModel.getData().remove(tabelReturnDetail.convertRowIndexToModel(index));
            returnDetailTableModel.fireTableDataChanged();
            
            textNofaktur.setText(null);
            textTanggalFaktur.setValue(null);
            textKodeObat.setText(null);
            textExpDate.setText(null);
            textJumlah.setValue(0);
            textTotal.setValue(getTotal());
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaruActionPerformed
        // TODO add your handling code here:
        textKodePbf.setText(null);
        textNamaPbf.setText(null);
        textNomorReturn.setText(null);
        textTanggalReturn.setValue(new Date());
        textNofaktur.setText(null);
        textTanggalFaktur.setValue(null);
        textKodeObat.setText(null);
        textExpDate.setText(null);
        textJumlah.setValue(0);
        
        returnDetailTableModel.getData().removeAllElements();
        returnDetailTableModel.fireTableDataChanged();
        textJumlah.setValue(0);
         
        returnDetailTableModel.getData().removeAllElements();
        returnDetailTableModel.fireTableDataChanged();
         textTotal.setValue(getTotal());
    }//GEN-LAST:event_buttonBaruActionPerformed

    private void textKuantitiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_textKuantitiStateChanged
        // TODO add your handling code here:
        textJumlah.setValue(getJumlah());
    }//GEN-LAST:event_textKuantitiStateChanged

    private void tabelReturnDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelReturnDetailMouseClicked
        // TODO add your handling code here:
         int index = tabelReturnDetail.getSelectedRow();
        ReturnDetail returnDetail = returnDetailTableModel.getData().get(tabelReturnDetail.convertRowIndexToModel(index));
        
        textKodeObat.setText(returnDetail.getKode_obat());
        textKuantiti.setValue(returnDetail.getKuantiti());
        textHargaBeli.setValue(returnDetail.getHarga());
        textJumlah.setValue(returnDetail.getJumlah());
        textJumlah.setValue(returnDetail.getJumlah());
    }//GEN-LAST:event_tabelReturnDetailMouseClicked

    private void tabelReturnDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelReturnDetailKeyReleased
        // TODO add your handling code here:
        tabelReturnDetailMouseClicked(null);
    }//GEN-LAST:event_tabelReturnDetailKeyReleased

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
          try {
            connection.setAutoCommit(false);
            ReturnObat returnObat = new ReturnObat();
            returnObat.setNomor(textNomorReturn.getText());
            
            returnObat.setNofaktur(textNofaktur.getText());
            returnObat.setTanggal_return((Date)textTanggalReturn.getValue());
            returnObat.setKode_pbf(textKodePbf.getText());
            returnObat.setTotal(Integer.parseInt(textTotal.getValue().toString()));
            returnModel.insert(returnObat);
            
            //jurnal debet
            JurnalTransaksi jurnalDebet = new JurnalTransaksi();
            jurnalDebet.setTanggal(returnObat.getTanggal_return());
            jurnalDebet.setNomor_bukti(returnObat.getNomor());
            jurnalDebet.setKeterangan("Return Pembelian");
            jurnalDebet.setKode_rekening("1-1100");
            jurnalDebet.setTipe("JKM");
            jurnalDebet.setDebet(returnObat.getTotal());
            jurnalDebet.setKredit(0);
            jurnalTransaksiModel.insert(jurnalDebet); 
            
            for (ReturnDetail dataTable : returnDetailTableModel.getData()){
                returnDetailModel.insert(dataTable);
                
            //jurnal kredit
            JurnalTransaksi jurnalKredit = new JurnalTransaksi();
            jurnalKredit.setTanggal(returnObat.getTanggal_return());
            jurnalKredit.setNomor_bukti(returnObat.getNomor());
            jurnalKredit.setKeterangan("Return Pembelian");
            jurnalKredit.setKode_rekening("1-1100");
            jurnalKredit.setTipe("JKM");
            jurnalKredit.setDebet(0);
            jurnalKredit.setKredit(dataTable.getJumlah());
            jurnalTransaksiModel.insert(jurnalKredit);   
            
            //mutasi
            MutasiObat mutasiObat = new MutasiObat();
            mutasiObat.setTanggal(returnObat.getTanggal_return());
            mutasiObat.setNomor_bukti(returnObat.getNomor());
            mutasiObat.setKeterangan("Return Pembelian");
            mutasiObat.setKode_obat(dataTable.getKode_obat());
            mutasiObat.setMasuk_kuantiti(0);
            mutasiObat.setMasuk_jumlah(0);
            mutasiObat.setKeluar_kuantiti(dataTable.getKuantiti());
            mutasiObat.setKeluar_jumlah(dataTable.getJumlah());
            mutasiObatModel.insert(mutasiObat);
            }
            
            connection.commit();
            JOptionPane.showMessageDialog(this, "data berhasil disimpan", "informasi", JOptionPane.INFORMATION_MESSAGE);
            //buttonBaruActionPerformed(evt);
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "data gagal disimpan", "informasi", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(PenjualanForm.class.getName()).log(Level.SEVERE, null, ex);
            try{
                connection.rollback();
            }catch (SQLException exl) {
                Logger.getLogger(PenjualanForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        HashMap parameter = new HashMap();
        Vector<HashMap> dataDetail = new Vector<HashMap>();
        
        int i = 1;
        for(ReturnDetail entity : returnDetailTableModel.getData()){
            HashMap row = new HashMap();
            row.put("kode_pbf", textKodePbf.getText());
            row.put("nama_pbf", textNamaPbf.getText());
            row.put("no_faktur", textNofaktur.getText());
            row.put("no_return", textNomorReturn.getText());
            row.put("tanggal", (Date) textTanggalReturn.getValue());
            
            row.put("detail_nomor", i++);
            row.put("detail_kode_obat", entity.getKode_obat());
            row.put("detail_kuantiti", entity.getKuantiti());
            row.put("detail_harga", entity.getHarga());
            row.put("detail_jumlah", entity.getJumlah());
            row.put("total", Integer.parseInt(textTotal.getValue().toString()));
            dataDetail.add(row);
        }
        JRDataSource dataSource = new JRBeanCollectionDataSource(dataDetail);
        try{
            InputStream ReturnLaporanJasper = getClass().getResourceAsStream("ReturnLaporan.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(ReturnLaporanJasper, parameter, dataSource);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(PenjualanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBaru;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonObatFind;
    private javax.swing.JButton buttonPbfFind;
    private javax.swing.JButton buttonPembelianFind;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonSisipkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelReturnDetail;
    private javax.swing.JFormattedTextField textExpDate;
    private javax.swing.JFormattedTextField textHargaBeli;
    private javax.swing.JFormattedTextField textJumlah;
    private javax.swing.JTextField textKodeObat;
    private javax.swing.JTextField textKodePbf;
    private javax.swing.JSpinner textKuantiti;
    private javax.swing.JTextField textNamaPbf;
    private javax.swing.JTextField textNofaktur;
    private javax.swing.JTextField textNomorReturn;
    private javax.swing.JFormattedTextField textTanggalFaktur;
    private javax.swing.JSpinner textTanggalReturn;
    private javax.swing.JFormattedTextField textTotal;
    // End of variables declaration//GEN-END:variables
}
